lang = "hebrew"
[otzaria]
export_books_path = "../../new_books/אוצריא"
export_links_path = "../../new_books/links"
log_path = "../../new_books/log"
refs_all_file_path = "../../new_books/refs_all..csv"
books_metadata_file_path = "../../סקריפטים/books_metadata.json"
folder_metadata_file_path = "../../סקריפטים/folder_metadata.json"
folder_name_replacements_file_path = "תיקיות.csv"
file_name_replacements_file_path = "ספרים.csv"
old_books_path = "../../sefaria_export/ספרים/אוצריא"
api_books_path = "../../sefaria_api/ספרים/אוצריא"
delete_api_files = false

[sefaria]
toc_file = "../../new_export/table_of_contents.json"
json_folder = "../../new_export/json"
schemas_folder = "../../new_export/schemas"
links_folder = "../../new_export/links"
files_black_list_file_path = "../ספרים.TXT"
authors_black_files_list_file_path = "../מחברים.TXT"
